# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/moshushiyan/lab7_1/lab7.srcs/sources_1/ip/rom3/rom3.xci
# IP: The module: 'rom3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/moshushiyan/lab7_1/lab7.srcs/sources_1/ip/rom3/rom3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/moshushiyan/lab7_1/lab7.srcs/sources_1/ip/rom3/rom3.xci
# IP: The module: 'rom3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/moshushiyan/lab7_1/lab7.srcs/sources_1/ip/rom3/rom3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
